<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//first we redirect the main  / route after login to excel content
Route::redirect('/', '/excelcontent');

//route for getting viewing, importing and exporting excel content
Route::get('/excelcontent', [Controllers\ExcelContentController::class, 'index'])
->name('excelcontent.index');

//route for exporting excel contents
Route::get('/excelcontent/export', [Controllers\ExcelContentController::class, 'export'])
->name('excelcontent.export');

//route for importing excel contents
Route::get('/excelcontent/import', [Controllers\ExcelContentController::class, 'show'])
->name('excelcontent.show');
Route::post('/excelcontent/import', [Controllers\ExcelContentController::class, 'store'])
->name('excelcontent.store');

// Route::get('livewire-datatables', function(){
//     return view('dashboard');
// });

//main dashboard route, default generated by laravel breeze auth
// Route::get('/dashboard', function () {
//     //variable holding the data for the marvel api
// $marvel_characters_response = Http::get('https://gateway.marvel.com/v1/public/characters', 
// [
//     'apikey'=> '79b29ec0804b795cf3be8ecb0985fdb5',
//     'ts'=>1,
//     'hash'=>'ffd4fa489d420f37f34e7c46be4632d3'
// ]);
//     return view('dashboard', ['marvel_characters' => $marvel_characters_response]);
// })->middleware(['auth'])->name('dashboard');

//route for getting viewing, importing and exporting excel content
Route::get('/dashboard', [Controllers\DashboardController::class, 'index'])
->name('dashboard');

require __DIR__.'/auth.php';
